### ISSUE TITLE
ShadowRoot needed?

### ISSUE THREAD

**Issue by dirkf** [JustOff/github-wc-polyfill#19]
SeaMonkey 2.53.6 Linux/x86

Sometimes (eg, [Commits list](https://github.com/JustOff/github-wc-polyfill/commits/master), go to commit, go back) Alt+<- (Back) fails: a blue progress indicator extends across the top of the page but no content appears under the page header.

This appears in the console:
```
ReferenceError: ShadowRoot is not defined[Learn More]  index.js:234:12
```
SM developer tools can't find `index.js`.

I added this minimal ShadowRoot polyfill for github.githubassets.com using NoScript:
```
if (!window.ShadowRoot) {
  window.ShadowRoot = function (init) {
    var _doc = new Document();
    Object.defineProperty(this, 'activeElement', {
      get: function () {
        return _doc.activeElement;
      }
    });
    Object.defineProperty(this, 'fullscreenElement', {
      get: function () {
        return _doc.fullscreenElement;
      }
    });
    Object.defineProperty(this, 'innerHTML', {
      get: function () {
        return _doc.innerHTML;
      },
      set: function (h) {
        _doc.innerHTML = h;
      }
    });
    Object.defineProperty(this, 'getSelection', function () {
      return _doc.defaultView.getSelection();
    });
    Object.defineProperty(this, 'elementFromPoint', function (x, y) {
      return _doc.elementFromPoint(x, y);
    });
    init = init || {
    };
    this.delegatesFocus = init.delegatesFocus;
    this.host = null;
    this.mode = init.mode || 'open';
    return _doc.documentElement;
  }
}
if (!Boolean(HTMLElement.prototype.shadowRoot)) {
  HTMLElement.prototype.shadowRoot = null;
}
if (!Boolean(HTMLElement.prototype.attachShadow)) HTMLElement.prototype.attachShadow = function (shadowInit) {
  var shad = new ShadowRoot(shadowInit);
  var shadowElt = shad.documentElement;
  this.shadowRoot = (shadowInit.mode === 'closed') ? null : shadowElt;
  Object.defineProperty(shad, 'host', this);
  return shadowElt;
}
```
I've no idea how much ShadowRoot functionality is being used, but this seems to fix the problem.

**Comment by JustOff** [comment]
Could you please provide exact steps to reproduce this error and link to the source of the polifill above?

**Comment by rofl0r** [comment]
> Sometimes (eg, Commits list, go to commit, go back) Alt+<- (Back) fails: a blue progress indicator extends across the top of the page but no content appears under the page header.

this happens also with palemoon, i'd say about every 10th time one clicks the back button while navigating on github.

**Comment by JustOff** [comment]
Unfortunately I still can't reproduce the error. [Here](https://github.githubassets.com/assets/compat-838cedbb.js) is the GitHub polyfill injected by the extension, and it has `ShadowRoot`.

**Comment by AroKol78** [comment]
especially when you jump to a specific comment (the comment is marked) and want to come back later

**Comment by dirkf** [comment]
I can't remember exactly how the polyfill code came about but it's entirely possible that I sat for a few minutes with MDN ShadowRoot doc in one window and JS Scratchpad in another: it looks like the sort of simple-minded stuff I could have written, and isn't obviously known to Google.

Looking at the GH polyfill it has Element.AttachShadow() and tests `window.ShadowRoot`, but I can't see it being defined - am I missing s/t?

In the browser I have NoScript active with github.com and github.githubassets.com enabled for JS, and no surrogates affecting those sites (unless I enable my polyfill).

Using the Commits page for this extension I was able to trigger the issue quite quickly, more than the 10% quoted by @rofl0r.

**Comment by dilworks** [comment]
Starting from today, I'm getting this error on EVERY GitHub page (even after updating your addon to 1.2.11):

TypeError: this.attachShadow is not a function

Some stuff is now broken to me:
- Trying to open the user menu just brings a blank menu with an unhelpful and totally modern "Sorry, something went wrong" message.
- I'm trying to delete an accidentally forked repo, but if you go to your repositories page and click on the dropdown menu on any repo (after the "Star" button), instead of a dropdown menu, you get an endless spinning wheel animation.

**Comment by dilworks** [comment]
Oh, awesome, can't even edit messages anymore because that dropdown menu is broken too!

Forgot to say: my browser is SeaMonkey 2.53.10.2 on Debian Linux 10 amd64
