### ISSUE TITLE
"Go to File" button not working any more

### ISSUE THREAD

**Issue by patrick-g2** [JustOff/github-wc-polyfill#35]
When clicking the "go to file" on the Code page, only the first file is displayed and typing a pattern has no effect.
Palemoon 29.4.1 error console displays 3 occurrences of:
Horodatage : 24/10/2021 19:04:43
Erreur : TypeError: t.replaceChildren is not a function
Fichier source : https://github.githubassets.com/assets/behaviors-f1867c3e.js
Ligne : 1
With "t" replaced by "e" or "this"
Tried on several repo, same result.
Works in Firefox ESR 91.2
